<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Maverick.DataAccess\**" />
    <Compile Remove="Maverick.Models\**" />
    <Content Remove="Maverick.DataAccess\**" />
    <Content Remove="Maverick.Models\**" />
    <EmbeddedResource Remove="Maverick.DataAccess\**" />
    <EmbeddedResource Remove="Maverick.Models\**" />
    <None Remove="Maverick.DataAccess\**" />
    <None Remove="Maverick.Models\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.21" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Maverick.DataAccess\Maverick.DataAccess.csproj" />
    <ProjectReference Include="..\Maverick.Models\Maverick.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Login\" />
  </ItemGroup>

</Project>
